language: java

secure: "qEO3SMNutn8n1orsZUdzViV6CWDGagSXhj89PxRQ3Guh+4gSbil55oRNjsCvVa7D1PnwpXxAaBE8UihxFBXIW8hUX676Y1c08GurL1tz0Ic8Wm83klj+duAmnaZNP1NBFhP5SECnQl4/v82WOjem4xCWRx2xjXzkRm42SyiQOWkpvaCPciay/Ze5NAPvF3NzO/vg2jo/t2RCJMbIMfOVT9ui4hQtI+NjykJ/EucLDufkZ1IQBrDRcx/7YDxW4D+mn+27QPPGqqyxA1zlMdqQCmy/uACKyQYH/eMOKZd6neFXry3ozrsN9y/HJ5L/ebW8ddU6BXaohquFl0Yssn1x4zjcHGK52265tEWSb9fWvf1kuC5tl+EvBU1EE9eTG2/B0mLiRqNb2xzZk9R7LntCDr+0coq1f3DLsRlo+/ZuufqOS86/Hs5GSq0KSVqW2SQtteVaLu1ZPTUB1puZpgNINaMlusz/hSCrJXKQ6E5457Wd+qOO7hCSE++VH8eJ2xYNGTrYcEjwR65L3AqrinorwcBa3RH6HGL4E4rmqI317fXYo91xgYnmlIRmAED/gyTRq/Q9UcuhgU9CxEiKrlADQivaWU1hOJtbmB6Alh+n4a+S0esmuEeWH2H6I8Tp9dgdZ1w8jtVf1Yr3rqaiR+DEHnZZjB9pDB0X7X9Z54sklVk="

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: staging